DESTDIR=$(CURDIR)/debian/firefox-quantum
firefox = "firefox-58.0.1.tar.bz2"

install:
	mkdir -p $(DESTDIR)/opt/
	mkdir -p $(DESTDIR)/usr/share/applications/
	tar -C $(DESTDIR)/opt -xvf "../${firefox}"
	install -m 0644 ../firefox-quantum.desktop $(DESTDIR)/usr/share/applications/
